# Generated by Django 5.1.3 on 2024-11-19 18:30

import exhibitions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='exhibition_images/', validators=[exhibitions.validators.validate_file_size, exhibitions.validators.validate_file_extension])),
            ],
        ),
    ]
